MESSAGE(STATUS "looking: ${LIBXSMM_DIR}")
FIND_LIBRARY(LIBXSMM_LIBRARY NAMES xsmm HINTS ${LIBXSMM_DIR}/lib)

IF(NOT LIBXSMM_LIBRARY)
    MESSAGE(FATAL_ERROR "Could not find libxsmm")
ELSE()
    MESSAGE(STATUS "Found libxssm: ${LIBXSMM_LIBRARY}")
ENDIF()

INCLUDE_DIRECTORIES(${LIBXSMM_DIR}/include)
